version: v1
name: nivesfdepot-scanner
type: workflow
tags:
  - snowflake
  - scanner
description: The job scans schema tables and register metadata
workflow:
  dag:
    - name: snowflakedepotjob
      description: The job scans schema from snowflake depot tables and register metadata to metis
      spec:
        stack: scanner:2.0
        compute: runnable-default
        stackSpec:
          depot: dataos://nivesfdepot          # snowflake depot name