name: nivesfdepot                                                     # Name of Depot
version: v2alpha                                                      # Version
type: depot                                                           # Type of file
tags:                                                                 # Tags used to fetch this document
  - Snowflake depot
  - user data
layer: user
depot:                                                                # Depot parameters
  type: snowflake                                                     # Type of data source
  description: Depot to fetch data from SNowflake datasource          # Description of the depot
  snowflake:                                                          # Snowflake parameters 
    warehouse: COMPUTE_WH                                             # Warehouse name
    url: sdxanuy-wr48932.snowflakecomputing.com                       # Individual Snowflake account URL - remove https://
    database: TMDC_V1                                                 # Database name
  external: true
  secrets:                                                             # Instance Secret Reference
    - name: nivesfdepot-r                                              # Read Instance file
      keys: 
        - nivesfdepot-r
      allkeys: true

    - name: nivesfdepot-rw                                             # Read-Write Instance file
      keys: 
        - nivesfdepot-rw
      allkeys: true