name: cost-efficiency-api
version: v1
type: service
tags:
  - service
  - dataos:type:resource
  - dataos:resource:service
  - dataos:layer:user
description: Talos Service
workspace: public
service:
  servicePort: 3000
  ingress:
    enabled: true
    stripPath: true
    path: /talos/public:cost-efficiency-api
    noAuthentication: true
  replicas: 1
  logLevel: DEBUG
  compute: runnable-default
  envs:
    TALOS_SCHEMA_PATH: tmdc-sf/activation/data-apis
    TALOS_BASE_PATH: /talos/public:cost-efficiency-api
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  stack: talos:2.0
  dataosSecrets:
    - name: userengagement-r
      allKeys: true
  stackSpec:
    repo:
      url: https://github.com/Acies-Nivedhaa/tmdc-sf
      projectDirectory: tmdc-sf/activation/data-apis
      syncFlags:
        - --ref=main